// Code generated by BobGen psql v0.40.2. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var CCarDriverErrors = &cCarDriverErrors{
	ErrUniqueCCarDriverPkey: &UniqueConstraintError{
		schema:  "",
		table:   "c_car_driver",
		columns: []string{"id"},
		s:       "c_car_driver_pkey",
	},
}

type cCarDriverErrors struct {
	ErrUniqueCCarDriverPkey *UniqueConstraintError
}
