// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var CCarClassErrors = &cCarClassErrors{
	ErrUniqueCCarClassPkey: &UniqueConstraintError{
		schema:  "",
		table:   "c_car_class",
		columns: []string{"id"},
		s:       "c_car_class_pkey",
	},
}

type cCarClassErrors struct {
	ErrUniqueCCarClassPkey *UniqueConstraintError
}
