// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var CCarEntryErrors = &cCarEntryErrors{
	ErrUniqueCCarEntryPkey: &UniqueConstraintError{
		schema:  "",
		table:   "c_car_entry",
		columns: []string{"id"},
		s:       "c_car_entry_pkey",
	},
}

type cCarEntryErrors struct {
	ErrUniqueCCarEntryPkey *UniqueConstraintError
}
