// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var CCarErrors = &cCarErrors{
	ErrUniqueCCarPkey: &UniqueConstraintError{
		schema:  "",
		table:   "c_car",
		columns: []string{"id"},
		s:       "c_car_pkey",
	},
}

type cCarErrors struct {
	ErrUniqueCCarPkey *UniqueConstraintError
}
