// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var CarStateProtoErrors = &carStateProtoErrors{
	ErrUniqueCarStateProtoPkey: &UniqueConstraintError{
		schema:  "",
		table:   "car_state_proto",
		columns: []string{"id"},
		s:       "car_state_proto_pkey",
	},
}

type carStateProtoErrors struct {
	ErrUniqueCarStateProtoPkey *UniqueConstraintError
}
