// Code generated by BobGen psql v0.40.2. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var EventExtErrors = &eventExtErrors{
	ErrUniqueEventExtPkey: &UniqueConstraintError{
		schema:  "",
		table:   "event_ext",
		columns: []string{"event_id"},
		s:       "event_ext_pkey",
	},
}

type eventExtErrors struct {
	ErrUniqueEventExtPkey *UniqueConstraintError
}
