// Code generated by BobGen psql v0.40.2. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var EventErrors = &eventErrors{
	ErrUniqueEventPkey: &UniqueConstraintError{
		schema:  "",
		table:   "event",
		columns: []string{"id"},
		s:       "event_pkey",
	},

	ErrUniqueEventEventKeyKey: &UniqueConstraintError{
		schema:  "",
		table:   "event",
		columns: []string{"event_key"},
		s:       "event_event_key_key",
	},
}

type eventErrors struct {
	ErrUniqueEventPkey *UniqueConstraintError

	ErrUniqueEventEventKeyKey *UniqueConstraintError
}
