// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var MSGStateProtoErrors = &msgStateProtoErrors{
	ErrUniqueMsgStateProtoPkey: &UniqueConstraintError{
		schema:  "",
		table:   "msg_state_proto",
		columns: []string{"id"},
		s:       "msg_state_proto_pkey",
	},
}

type msgStateProtoErrors struct {
	ErrUniqueMsgStateProtoPkey *UniqueConstraintError
}
