// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var RaceStateProtoErrors = &raceStateProtoErrors{
	ErrUniqueRaceStateProtoPkey: &UniqueConstraintError{
		schema:  "",
		table:   "race_state_proto",
		columns: []string{"id"},
		s:       "race_state_proto_pkey",
	},
}

type raceStateProtoErrors struct {
	ErrUniqueRaceStateProtoPkey *UniqueConstraintError
}
