// Code generated by BobGen psql v0.40.2. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var TenantErrors = &tenantErrors{
	ErrUniqueTenantPkey: &UniqueConstraintError{
		schema:  "",
		table:   "tenant",
		columns: []string{"id"},
		s:       "tenant_pkey",
	},

	ErrUniqueTenantApiKeyUnique: &UniqueConstraintError{
		schema:  "",
		table:   "tenant",
		columns: []string{"api_key"},
		s:       "tenant_api_key_unique",
	},

	ErrUniqueTenantExternalIdUnique: &UniqueConstraintError{
		schema:  "",
		table:   "tenant",
		columns: []string{"external_id"},
		s:       "tenant_external_id_unique",
	},

	ErrUniqueTenantNameUnique: &UniqueConstraintError{
		schema:  "",
		table:   "tenant",
		columns: []string{"name"},
		s:       "tenant_name_unique",
	},
}

type tenantErrors struct {
	ErrUniqueTenantPkey *UniqueConstraintError

	ErrUniqueTenantApiKeyUnique *UniqueConstraintError

	ErrUniqueTenantExternalIdUnique *UniqueConstraintError

	ErrUniqueTenantNameUnique *UniqueConstraintError
}
