// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"

	"github.com/aarondl/opt/omit"
	mytypes "github.com/mpapenbr/iracelog-service-manager-go/pkg/db/mytypes"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// EventExt is an object representing the database table.
type EventExt struct {
	EventID   int32                   `db:"event_id,pk" `
	ExtraInfo mytypes.CustomExtraInfo `db:"extra_info" `

	R eventExtR `db:"-" `
}

// EventExtSlice is an alias for a slice of pointers to EventExt.
// This should almost always be used instead of []*EventExt.
type EventExtSlice []*EventExt

// EventExts contains methods to work with the event_ext table
var EventExts = psql.NewTablex[*EventExt, EventExtSlice, *EventExtSetter]("", "event_ext", buildEventExtColumns("event_ext"))

// EventExtsQuery is a query on the event_ext table
type EventExtsQuery = *psql.ViewQuery[*EventExt, EventExtSlice]

// eventExtR is where relationships are stored.
type eventExtR struct {
	Event *Event // event_ext.event_ext_event_id_fkey
}

func buildEventExtColumns(alias string) eventExtColumns {
	return eventExtColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"event_id", "extra_info",
		).WithParent("event_ext"),
		tableAlias: alias,
		EventID:    psql.Quote(alias, "event_id"),
		ExtraInfo:  psql.Quote(alias, "extra_info"),
	}
}

type eventExtColumns struct {
	expr.ColumnsExpr
	tableAlias string
	EventID    psql.Expression
	ExtraInfo  psql.Expression
}

func (c eventExtColumns) Alias() string {
	return c.tableAlias
}

func (eventExtColumns) AliasedAs(alias string) eventExtColumns {
	return buildEventExtColumns(alias)
}

// EventExtSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type EventExtSetter struct {
	EventID   omit.Val[int32]                   `db:"event_id,pk" `
	ExtraInfo omit.Val[mytypes.CustomExtraInfo] `db:"extra_info" `
}

func (s EventExtSetter) SetColumns() []string {
	vals := make([]string, 0, 2)
	if s.EventID.IsValue() {
		vals = append(vals, "event_id")
	}
	if s.ExtraInfo.IsValue() {
		vals = append(vals, "extra_info")
	}
	return vals
}

func (s EventExtSetter) Overwrite(t *EventExt) {
	if s.EventID.IsValue() {
		t.EventID = s.EventID.MustGet()
	}
	if s.ExtraInfo.IsValue() {
		t.ExtraInfo = s.ExtraInfo.MustGet()
	}
}

func (s *EventExtSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return EventExts.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 2)
		if s.EventID.IsValue() {
			vals[0] = psql.Arg(s.EventID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.ExtraInfo.IsValue() {
			vals[1] = psql.Arg(s.ExtraInfo.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s EventExtSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s EventExtSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 2)

	if s.EventID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "event_id")...),
			psql.Arg(s.EventID),
		}})
	}

	if s.ExtraInfo.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "extra_info")...),
			psql.Arg(s.ExtraInfo),
		}})
	}

	return exprs
}

// FindEventExt retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindEventExt(ctx context.Context, exec bob.Executor, EventIDPK int32, cols ...string) (*EventExt, error) {
	if len(cols) == 0 {
		return EventExts.Query(
			sm.Where(EventExts.Columns.EventID.EQ(psql.Arg(EventIDPK))),
		).One(ctx, exec)
	}

	return EventExts.Query(
		sm.Where(EventExts.Columns.EventID.EQ(psql.Arg(EventIDPK))),
		sm.Columns(EventExts.Columns.Only(cols...)),
	).One(ctx, exec)
}

// EventExtExists checks the presence of a single record by primary key
func EventExtExists(ctx context.Context, exec bob.Executor, EventIDPK int32) (bool, error) {
	return EventExts.Query(
		sm.Where(EventExts.Columns.EventID.EQ(psql.Arg(EventIDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after EventExt is retrieved from the database
func (o *EventExt) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = EventExts.AfterSelectHooks.RunHooks(ctx, exec, EventExtSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = EventExts.AfterInsertHooks.RunHooks(ctx, exec, EventExtSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = EventExts.AfterUpdateHooks.RunHooks(ctx, exec, EventExtSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = EventExts.AfterDeleteHooks.RunHooks(ctx, exec, EventExtSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the EventExt
func (o *EventExt) primaryKeyVals() bob.Expression {
	return psql.Arg(o.EventID)
}

func (o *EventExt) pkEQ() dialect.Expression {
	return psql.Quote("event_ext", "event_id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the EventExt
func (o *EventExt) Update(ctx context.Context, exec bob.Executor, s *EventExtSetter) error {
	v, err := EventExts.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single EventExt record with an executor
func (o *EventExt) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := EventExts.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the EventExt using the executor
func (o *EventExt) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := EventExts.Query(
		sm.Where(EventExts.Columns.EventID.EQ(psql.Arg(o.EventID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after EventExtSlice is retrieved from the database
func (o EventExtSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = EventExts.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = EventExts.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = EventExts.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = EventExts.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o EventExtSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("event_ext", "event_id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o EventExtSlice) copyMatchingRows(from ...*EventExt) {
	for i, old := range o {
		for _, new := range from {
			if new.EventID != old.EventID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o EventExtSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return EventExts.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *EventExt:
				o.copyMatchingRows(retrieved)
			case []*EventExt:
				o.copyMatchingRows(retrieved...)
			case EventExtSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a EventExt or a slice of EventExt
				// then run the AfterUpdateHooks on the slice
				_, err = EventExts.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o EventExtSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return EventExts.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *EventExt:
				o.copyMatchingRows(retrieved)
			case []*EventExt:
				o.copyMatchingRows(retrieved...)
			case EventExtSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a EventExt or a slice of EventExt
				// then run the AfterDeleteHooks on the slice
				_, err = EventExts.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o EventExtSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals EventExtSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := EventExts.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o EventExtSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := EventExts.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o EventExtSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := EventExts.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// Event starts a query for related objects on event
func (o *EventExt) Event(mods ...bob.Mod[*dialect.SelectQuery]) EventsQuery {
	return Events.Query(append(mods,
		sm.Where(Events.Columns.ID.EQ(psql.Arg(o.EventID))),
	)...)
}

func (os EventExtSlice) Event(mods ...bob.Mod[*dialect.SelectQuery]) EventsQuery {
	pkEventID := make(pgtypes.Array[int32], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkEventID = append(pkEventID, o.EventID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkEventID), "integer[]")),
	))

	return Events.Query(append(mods,
		sm.Where(psql.Group(Events.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

func attachEventExtEvent0(ctx context.Context, exec bob.Executor, count int, eventExt0 *EventExt, event1 *Event) (*EventExt, error) {
	setter := &EventExtSetter{
		EventID: omit.From(event1.ID),
	}

	err := eventExt0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachEventExtEvent0: %w", err)
	}

	return eventExt0, nil
}

func (eventExt0 *EventExt) InsertEvent(ctx context.Context, exec bob.Executor, related *EventSetter) error {
	var err error

	event1, err := Events.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachEventExtEvent0(ctx, exec, 1, eventExt0, event1)
	if err != nil {
		return err
	}

	eventExt0.R.Event = event1

	event1.R.EventExt = eventExt0

	return nil
}

func (eventExt0 *EventExt) AttachEvent(ctx context.Context, exec bob.Executor, event1 *Event) error {
	var err error

	_, err = attachEventExtEvent0(ctx, exec, 1, eventExt0, event1)
	if err != nil {
		return err
	}

	eventExt0.R.Event = event1

	event1.R.EventExt = eventExt0

	return nil
}

type eventExtWhere[Q psql.Filterable] struct {
	EventID   psql.WhereMod[Q, int32]
	ExtraInfo psql.WhereMod[Q, mytypes.CustomExtraInfo]
}

func (eventExtWhere[Q]) AliasedAs(alias string) eventExtWhere[Q] {
	return buildEventExtWhere[Q](buildEventExtColumns(alias))
}

func buildEventExtWhere[Q psql.Filterable](cols eventExtColumns) eventExtWhere[Q] {
	return eventExtWhere[Q]{
		EventID:   psql.Where[Q, int32](cols.EventID),
		ExtraInfo: psql.Where[Q, mytypes.CustomExtraInfo](cols.ExtraInfo),
	}
}

func (o *EventExt) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "Event":
		rel, ok := retrieved.(*Event)
		if !ok {
			return fmt.Errorf("eventExt cannot load %T as %q", retrieved, name)
		}

		o.R.Event = rel

		if rel != nil {
			rel.R.EventExt = o
		}
		return nil
	default:
		return fmt.Errorf("eventExt has no relationship %q", name)
	}
}

type eventExtPreloader struct {
	Event func(...psql.PreloadOption) psql.Preloader
}

func buildEventExtPreloader() eventExtPreloader {
	return eventExtPreloader{
		Event: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*Event, EventSlice](psql.PreloadRel{
				Name: "Event",
				Sides: []psql.PreloadSide{
					{
						From:        EventExts,
						To:          Events,
						FromColumns: []string{"event_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Events.Columns.Names(), opts...)
		},
	}
}

type eventExtThenLoader[Q orm.Loadable] struct {
	Event func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildEventExtThenLoader[Q orm.Loadable]() eventExtThenLoader[Q] {
	type EventLoadInterface interface {
		LoadEvent(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return eventExtThenLoader[Q]{
		Event: thenLoadBuilder[Q](
			"Event",
			func(ctx context.Context, exec bob.Executor, retrieved EventLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadEvent(ctx, exec, mods...)
			},
		),
	}
}

// LoadEvent loads the eventExt's Event into the .R struct
func (o *EventExt) LoadEvent(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Event = nil

	related, err := o.Event(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.EventExt = o

	o.R.Event = related
	return nil
}

// LoadEvent loads the eventExt's Event into the .R struct
func (os EventExtSlice) LoadEvent(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	events, err := os.Event(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range events {

			if !(o.EventID == rel.ID) {
				continue
			}

			rel.R.EventExt = o

			o.R.Event = rel
			break
		}
	}

	return nil
}

type eventExtJoins[Q dialect.Joinable] struct {
	typ   string
	Event modAs[Q, eventColumns]
}

func (j eventExtJoins[Q]) aliasedAs(alias string) eventExtJoins[Q] {
	return buildEventExtJoins[Q](buildEventExtColumns(alias), j.typ)
}

func buildEventExtJoins[Q dialect.Joinable](cols eventExtColumns, typ string) eventExtJoins[Q] {
	return eventExtJoins[Q]{
		typ: typ,
		Event: modAs[Q, eventColumns]{
			c: Events.Columns,
			f: func(to eventColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Events.Name().As(to.Alias())).On(
						to.ID.EQ(cols.EventID),
					))
				}

				return mods
			},
		},
	}
}
