// Code generated by BobGen psql v0.40.2. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"

	"github.com/aarondl/opt/omit"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// RaceStateProto is an object representing the database table.
type RaceStateProto struct {
	ID        int32  `db:"id,pk" `
	RSInfoID  int32  `db:"rs_info_id" `
	Protodata []byte `db:"protodata" `

	R raceStateProtoR `db:"-" `
}

// RaceStateProtoSlice is an alias for a slice of pointers to RaceStateProto.
// This should almost always be used instead of []*RaceStateProto.
type RaceStateProtoSlice []*RaceStateProto

// RaceStateProtos contains methods to work with the race_state_proto table
var RaceStateProtos = psql.NewTablex[*RaceStateProto, RaceStateProtoSlice, *RaceStateProtoSetter]("", "race_state_proto", buildRaceStateProtoColumns("race_state_proto"))

// RaceStateProtosQuery is a query on the race_state_proto table
type RaceStateProtosQuery = *psql.ViewQuery[*RaceStateProto, RaceStateProtoSlice]

// raceStateProtoR is where relationships are stored.
type raceStateProtoR struct {
	RSInfo *RSInfo // race_state_proto.race_state_proto_rs_info_id_fkey
}

func buildRaceStateProtoColumns(alias string) raceStateProtoColumns {
	return raceStateProtoColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "rs_info_id", "protodata",
		).WithParent("race_state_proto"),
		tableAlias: alias,
		ID:         psql.Quote(alias, "id"),
		RSInfoID:   psql.Quote(alias, "rs_info_id"),
		Protodata:  psql.Quote(alias, "protodata"),
	}
}

type raceStateProtoColumns struct {
	expr.ColumnsExpr
	tableAlias string
	ID         psql.Expression
	RSInfoID   psql.Expression
	Protodata  psql.Expression
}

func (c raceStateProtoColumns) Alias() string {
	return c.tableAlias
}

func (raceStateProtoColumns) AliasedAs(alias string) raceStateProtoColumns {
	return buildRaceStateProtoColumns(alias)
}

// RaceStateProtoSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type RaceStateProtoSetter struct {
	ID        omit.Val[int32]  `db:"id,pk" `
	RSInfoID  omit.Val[int32]  `db:"rs_info_id" `
	Protodata omit.Val[[]byte] `db:"protodata" `
}

func (s RaceStateProtoSetter) SetColumns() []string {
	vals := make([]string, 0, 3)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.RSInfoID.IsValue() {
		vals = append(vals, "rs_info_id")
	}
	if s.Protodata.IsValue() {
		vals = append(vals, "protodata")
	}
	return vals
}

func (s RaceStateProtoSetter) Overwrite(t *RaceStateProto) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.RSInfoID.IsValue() {
		t.RSInfoID = s.RSInfoID.MustGet()
	}
	if s.Protodata.IsValue() {
		t.Protodata = s.Protodata.MustGet()
	}
}

func (s *RaceStateProtoSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return RaceStateProtos.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 3)
		if s.ID.IsValue() {
			vals[0] = psql.Arg(s.ID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.RSInfoID.IsValue() {
			vals[1] = psql.Arg(s.RSInfoID.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.Protodata.IsValue() {
			vals[2] = psql.Arg(s.Protodata.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s RaceStateProtoSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s RaceStateProtoSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 3)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.RSInfoID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "rs_info_id")...),
			psql.Arg(s.RSInfoID),
		}})
	}

	if s.Protodata.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "protodata")...),
			psql.Arg(s.Protodata),
		}})
	}

	return exprs
}

// FindRaceStateProto retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindRaceStateProto(ctx context.Context, exec bob.Executor, IDPK int32, cols ...string) (*RaceStateProto, error) {
	if len(cols) == 0 {
		return RaceStateProtos.Query(
			sm.Where(RaceStateProtos.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return RaceStateProtos.Query(
		sm.Where(RaceStateProtos.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(RaceStateProtos.Columns.Only(cols...)),
	).One(ctx, exec)
}

// RaceStateProtoExists checks the presence of a single record by primary key
func RaceStateProtoExists(ctx context.Context, exec bob.Executor, IDPK int32) (bool, error) {
	return RaceStateProtos.Query(
		sm.Where(RaceStateProtos.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after RaceStateProto is retrieved from the database
func (o *RaceStateProto) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = RaceStateProtos.AfterSelectHooks.RunHooks(ctx, exec, RaceStateProtoSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = RaceStateProtos.AfterInsertHooks.RunHooks(ctx, exec, RaceStateProtoSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = RaceStateProtos.AfterUpdateHooks.RunHooks(ctx, exec, RaceStateProtoSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = RaceStateProtos.AfterDeleteHooks.RunHooks(ctx, exec, RaceStateProtoSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the RaceStateProto
func (o *RaceStateProto) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *RaceStateProto) pkEQ() dialect.Expression {
	return psql.Quote("race_state_proto", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the RaceStateProto
func (o *RaceStateProto) Update(ctx context.Context, exec bob.Executor, s *RaceStateProtoSetter) error {
	v, err := RaceStateProtos.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single RaceStateProto record with an executor
func (o *RaceStateProto) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := RaceStateProtos.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the RaceStateProto using the executor
func (o *RaceStateProto) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := RaceStateProtos.Query(
		sm.Where(RaceStateProtos.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after RaceStateProtoSlice is retrieved from the database
func (o RaceStateProtoSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = RaceStateProtos.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = RaceStateProtos.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = RaceStateProtos.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = RaceStateProtos.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o RaceStateProtoSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("race_state_proto", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o RaceStateProtoSlice) copyMatchingRows(from ...*RaceStateProto) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o RaceStateProtoSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return RaceStateProtos.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *RaceStateProto:
				o.copyMatchingRows(retrieved)
			case []*RaceStateProto:
				o.copyMatchingRows(retrieved...)
			case RaceStateProtoSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a RaceStateProto or a slice of RaceStateProto
				// then run the AfterUpdateHooks on the slice
				_, err = RaceStateProtos.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o RaceStateProtoSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return RaceStateProtos.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *RaceStateProto:
				o.copyMatchingRows(retrieved)
			case []*RaceStateProto:
				o.copyMatchingRows(retrieved...)
			case RaceStateProtoSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a RaceStateProto or a slice of RaceStateProto
				// then run the AfterDeleteHooks on the slice
				_, err = RaceStateProtos.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o RaceStateProtoSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals RaceStateProtoSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := RaceStateProtos.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o RaceStateProtoSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := RaceStateProtos.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o RaceStateProtoSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := RaceStateProtos.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// RSInfo starts a query for related objects on rs_info
func (o *RaceStateProto) RSInfo(mods ...bob.Mod[*dialect.SelectQuery]) RSInfosQuery {
	return RSInfos.Query(append(mods,
		sm.Where(RSInfos.Columns.ID.EQ(psql.Arg(o.RSInfoID))),
	)...)
}

func (os RaceStateProtoSlice) RSInfo(mods ...bob.Mod[*dialect.SelectQuery]) RSInfosQuery {
	pkRSInfoID := make(pgtypes.Array[int32], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkRSInfoID = append(pkRSInfoID, o.RSInfoID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkRSInfoID), "integer[]")),
	))

	return RSInfos.Query(append(mods,
		sm.Where(psql.Group(RSInfos.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

func attachRaceStateProtoRSInfo0(ctx context.Context, exec bob.Executor, count int, raceStateProto0 *RaceStateProto, rsInfo1 *RSInfo) (*RaceStateProto, error) {
	setter := &RaceStateProtoSetter{
		RSInfoID: omit.From(rsInfo1.ID),
	}

	err := raceStateProto0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachRaceStateProtoRSInfo0: %w", err)
	}

	return raceStateProto0, nil
}

func (raceStateProto0 *RaceStateProto) InsertRSInfo(ctx context.Context, exec bob.Executor, related *RSInfoSetter) error {
	rsInfo1, err := RSInfos.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachRaceStateProtoRSInfo0(ctx, exec, 1, raceStateProto0, rsInfo1)
	if err != nil {
		return err
	}

	raceStateProto0.R.RSInfo = rsInfo1

	rsInfo1.R.RaceStateProtos = append(rsInfo1.R.RaceStateProtos, raceStateProto0)

	return nil
}

func (raceStateProto0 *RaceStateProto) AttachRSInfo(ctx context.Context, exec bob.Executor, rsInfo1 *RSInfo) error {
	var err error

	_, err = attachRaceStateProtoRSInfo0(ctx, exec, 1, raceStateProto0, rsInfo1)
	if err != nil {
		return err
	}

	raceStateProto0.R.RSInfo = rsInfo1

	rsInfo1.R.RaceStateProtos = append(rsInfo1.R.RaceStateProtos, raceStateProto0)

	return nil
}

type raceStateProtoWhere[Q psql.Filterable] struct {
	ID        psql.WhereMod[Q, int32]
	RSInfoID  psql.WhereMod[Q, int32]
	Protodata psql.WhereMod[Q, []byte]
}

func (raceStateProtoWhere[Q]) AliasedAs(alias string) raceStateProtoWhere[Q] {
	return buildRaceStateProtoWhere[Q](buildRaceStateProtoColumns(alias))
}

func buildRaceStateProtoWhere[Q psql.Filterable](cols raceStateProtoColumns) raceStateProtoWhere[Q] {
	return raceStateProtoWhere[Q]{
		ID:        psql.Where[Q, int32](cols.ID),
		RSInfoID:  psql.Where[Q, int32](cols.RSInfoID),
		Protodata: psql.Where[Q, []byte](cols.Protodata),
	}
}

func (o *RaceStateProto) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "RSInfo":
		rel, ok := retrieved.(*RSInfo)
		if !ok {
			return fmt.Errorf("raceStateProto cannot load %T as %q", retrieved, name)
		}

		o.R.RSInfo = rel

		if rel != nil {
			rel.R.RaceStateProtos = RaceStateProtoSlice{o}
		}
		return nil
	default:
		return fmt.Errorf("raceStateProto has no relationship %q", name)
	}
}

type raceStateProtoPreloader struct {
	RSInfo func(...psql.PreloadOption) psql.Preloader
}

func buildRaceStateProtoPreloader() raceStateProtoPreloader {
	return raceStateProtoPreloader{
		RSInfo: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*RSInfo, RSInfoSlice](psql.PreloadRel{
				Name: "RSInfo",
				Sides: []psql.PreloadSide{
					{
						From:        RaceStateProtos,
						To:          RSInfos,
						FromColumns: []string{"rs_info_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, RSInfos.Columns.Names(), opts...)
		},
	}
}

type raceStateProtoThenLoader[Q orm.Loadable] struct {
	RSInfo func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildRaceStateProtoThenLoader[Q orm.Loadable]() raceStateProtoThenLoader[Q] {
	type RSInfoLoadInterface interface {
		LoadRSInfo(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return raceStateProtoThenLoader[Q]{
		RSInfo: thenLoadBuilder[Q](
			"RSInfo",
			func(ctx context.Context, exec bob.Executor, retrieved RSInfoLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadRSInfo(ctx, exec, mods...)
			},
		),
	}
}

// LoadRSInfo loads the raceStateProto's RSInfo into the .R struct
func (o *RaceStateProto) LoadRSInfo(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.RSInfo = nil

	related, err := o.RSInfo(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.RaceStateProtos = RaceStateProtoSlice{o}

	o.R.RSInfo = related
	return nil
}

// LoadRSInfo loads the raceStateProto's RSInfo into the .R struct
func (os RaceStateProtoSlice) LoadRSInfo(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	rsInfos, err := os.RSInfo(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range rsInfos {

			if !(o.RSInfoID == rel.ID) {
				continue
			}

			rel.R.RaceStateProtos = append(rel.R.RaceStateProtos, o)

			o.R.RSInfo = rel
			break
		}
	}

	return nil
}

type raceStateProtoJoins[Q dialect.Joinable] struct {
	typ    string
	RSInfo modAs[Q, rsInfoColumns]
}

func (j raceStateProtoJoins[Q]) aliasedAs(alias string) raceStateProtoJoins[Q] {
	return buildRaceStateProtoJoins[Q](buildRaceStateProtoColumns(alias), j.typ)
}

func buildRaceStateProtoJoins[Q dialect.Joinable](cols raceStateProtoColumns, typ string) raceStateProtoJoins[Q] {
	return raceStateProtoJoins[Q]{
		typ: typ,
		RSInfo: modAs[Q, rsInfoColumns]{
			c: RSInfos.Columns,
			f: func(to rsInfoColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, RSInfos.Name().As(to.Alias())).On(
						to.ID.EQ(cols.RSInfoID),
					))
				}

				return mods
			},
		},
	}
}
