// Code generated by BobGen psql v0.48.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"

	"github.com/aarondl/opt/omit"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// SpeedmapProto is an object representing the database table.
type SpeedmapProto struct {
	ID        int32  `db:"id,pk" `
	RSInfoID  int32  `db:"rs_info_id" `
	Protodata []byte `db:"protodata" `

	R speedmapProtoR `db:"-" `
}

// SpeedmapProtoSlice is an alias for a slice of pointers to SpeedmapProto.
// This should almost always be used instead of []*SpeedmapProto.
type SpeedmapProtoSlice []*SpeedmapProto

// SpeedmapProtos contains methods to work with the speedmap_proto table
var SpeedmapProtos = psql.NewTablex[*SpeedmapProto, SpeedmapProtoSlice, *SpeedmapProtoSetter]("", "speedmap_proto", buildSpeedmapProtoColumns("speedmap_proto"))

// SpeedmapProtosQuery is a query on the speedmap_proto table
type SpeedmapProtosQuery = *psql.ViewQuery[*SpeedmapProto, SpeedmapProtoSlice]

// speedmapProtoR is where relationships are stored.
type speedmapProtoR struct {
	RSInfo *RSInfo // speedmap_proto.speedmap_proto_rs_info_id_fkey
	// Loaded reports whether each relationship has been loaded.
	// A relationship's bool is set by Load*, Preload, ThenLoad, factory builds,
	// and to-one Attach/Insert operations. To-many Attach/Insert operations leave it unchanged.
	Loaded speedmapProtoRLoaded `db:"-" `
}

// speedmapProtoRLoaded tracks which relationships on SpeedmapProto have been loaded.
type speedmapProtoRLoaded struct {
	RSInfo bool // speedmap_proto.speedmap_proto_rs_info_id_fkey
}

func buildSpeedmapProtoColumns(tableName string) speedmapProtoColumns {
	columnsExpr := expr.NewColumnsExpr(
		"id", "rs_info_id", "protodata",
	)

	if tableName != "" {
		columnsExpr = columnsExpr.WithParent(tableName)
	}

	return speedmapProtoColumns{
		ColumnsExpr: columnsExpr,
		tableAlias:  tableName,
		ID:          buildSpeedmapProtoColumn(tableName, "id"),
		RSInfoID:    buildSpeedmapProtoColumn(tableName, "rs_info_id"),
		Protodata:   buildSpeedmapProtoColumn(tableName, "protodata"),
	}
}

type speedmapProtoColumns struct {
	expr.ColumnsExpr
	tableAlias string
	ID         speedmapProtoColumn
	RSInfoID   speedmapProtoColumn
	Protodata  speedmapProtoColumn
}

// Alias returns the current table alias for the columns set.
func (c speedmapProtoColumns) Alias() string {
	return c.tableAlias
}

// AliasedAs returns a copy of the columns set qualified by tableName.
func (speedmapProtoColumns) AliasedAs(tableName string) speedmapProtoColumns {
	return buildSpeedmapProtoColumns(tableName)
}

// Unqualified returns a copy of the columns set without table qualification.
func (c speedmapProtoColumns) Unqualified() speedmapProtoColumns {
	return buildSpeedmapProtoColumns("")
}

func buildSpeedmapProtoColumn(alias, name string) speedmapProtoColumn {
	return speedmapProtoColumn{
		Expression: psql.Quote(alias, name),
		alias:      alias,
		name:       name,
	}
}

type speedmapProtoColumn struct {
	psql.Expression
	alias string
	name  string
}

// Name returns the unqualified column name.
func (c speedmapProtoColumn) Name() string {
	return c.name
}

// ShouldOmitParens prevents automatic parenthesis wrapping in expression builders.
func (c speedmapProtoColumn) ShouldOmitParens() bool {
	return true
}

// SpeedmapProtoSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type SpeedmapProtoSetter struct {
	ID        omit.Val[int32]  `db:"id,pk" `
	RSInfoID  omit.Val[int32]  `db:"rs_info_id" `
	Protodata omit.Val[[]byte] `db:"protodata" `
}

func (s SpeedmapProtoSetter) SetColumns() []string {
	vals := make([]string, 0, 3)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.RSInfoID.IsValue() {
		vals = append(vals, "rs_info_id")
	}
	if s.Protodata.IsValue() {
		vals = append(vals, "protodata")
	}
	return vals
}

func (s SpeedmapProtoSetter) Overwrite(t *SpeedmapProto) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.RSInfoID.IsValue() {
		t.RSInfoID = s.RSInfoID.MustGet()
	}
	if s.Protodata.IsValue() {
		t.Protodata = s.Protodata.MustGet()
	}
}

func (s *SpeedmapProtoSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return SpeedmapProtos.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(
		bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.ID.IsUnset() {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(s.ID.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.RSInfoID.IsUnset() {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(s.RSInfoID.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.Protodata.IsUnset() {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(s.Protodata.MustGet()).WriteSQL(ctx, w, d, start)
		}))
}

func (s SpeedmapProtoSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s SpeedmapProtoSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 3)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.RSInfoID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "rs_info_id")...),
			psql.Arg(s.RSInfoID),
		}})
	}

	if s.Protodata.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "protodata")...),
			psql.Arg(s.Protodata),
		}})
	}

	return exprs
}

// FindSpeedmapProto retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindSpeedmapProto(ctx context.Context, exec bob.Executor, IDPK int32, cols ...string) (*SpeedmapProto, error) {
	if len(cols) == 0 {
		return SpeedmapProtos.Query(
			sm.Where(SpeedmapProtos.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return SpeedmapProtos.Query(
		sm.Where(SpeedmapProtos.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(SpeedmapProtos.Columns.Only(cols...)),
	).One(ctx, exec)
}

// SpeedmapProtoExists checks the presence of a single record by primary key
func SpeedmapProtoExists(ctx context.Context, exec bob.Executor, IDPK int32) (bool, error) {
	return SpeedmapProtos.Query(
		sm.Where(SpeedmapProtos.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after SpeedmapProto is retrieved from the database
func (o *SpeedmapProto) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = SpeedmapProtos.AfterSelectHooks.RunHooks(ctx, exec, SpeedmapProtoSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = SpeedmapProtos.AfterInsertHooks.RunHooks(ctx, exec, SpeedmapProtoSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = SpeedmapProtos.AfterUpdateHooks.RunHooks(ctx, exec, SpeedmapProtoSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = SpeedmapProtos.AfterDeleteHooks.RunHooks(ctx, exec, SpeedmapProtoSlice{o})
	case bob.QueryTypeMerge:
		ctx, err = SpeedmapProtos.AfterMergeHooks.RunHooks(ctx, exec, SpeedmapProtoSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the SpeedmapProto
func (o *SpeedmapProto) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *SpeedmapProto) pkEQ() dialect.Expression {
	return psql.Quote("speedmap_proto", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the SpeedmapProto
func (o *SpeedmapProto) Update(ctx context.Context, exec bob.Executor, s *SpeedmapProtoSetter) error {
	v, err := SpeedmapProtos.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single SpeedmapProto record with an executor
func (o *SpeedmapProto) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := SpeedmapProtos.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the SpeedmapProto using the executor
func (o *SpeedmapProto) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := SpeedmapProtos.Query(
		sm.Where(SpeedmapProtos.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after SpeedmapProtoSlice is retrieved from the database
func (o SpeedmapProtoSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = SpeedmapProtos.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = SpeedmapProtos.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = SpeedmapProtos.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = SpeedmapProtos.AfterDeleteHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeMerge:
		ctx, err = SpeedmapProtos.AfterMergeHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o SpeedmapProtoSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("speedmap_proto", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o SpeedmapProtoSlice) copyMatchingRows(from ...*SpeedmapProto) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o SpeedmapProtoSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return SpeedmapProtos.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *SpeedmapProto:
				o.copyMatchingRows(retrieved)
			case []*SpeedmapProto:
				o.copyMatchingRows(retrieved...)
			case SpeedmapProtoSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a SpeedmapProto or a slice of SpeedmapProto
				// then run the AfterUpdateHooks on the slice
				_, err = SpeedmapProtos.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o SpeedmapProtoSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return SpeedmapProtos.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *SpeedmapProto:
				o.copyMatchingRows(retrieved)
			case []*SpeedmapProto:
				o.copyMatchingRows(retrieved...)
			case SpeedmapProtoSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a SpeedmapProto or a slice of SpeedmapProto
				// then run the AfterDeleteHooks on the slice
				_, err = SpeedmapProtos.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// MergeMod modifies a merge query to run BeforeMergeHooks and AfterMergeHooks
// and updates the slice with the returned rows.
func (o SpeedmapProtoSlice) MergeMod() bob.Mod[*dialect.MergeQuery] {
	return bob.ModFunc[*dialect.MergeQuery](func(q *dialect.MergeQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return SpeedmapProtos.BeforeMergeHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *SpeedmapProto:
				o.copyMatchingRows(retrieved)
			case []*SpeedmapProto:
				o.copyMatchingRows(retrieved...)
			case SpeedmapProtoSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a SpeedmapProto or a slice of SpeedmapProto
				// then run the AfterMergeHooks on the slice
				_, err = SpeedmapProtos.AfterMergeHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))
	})
}

func (o SpeedmapProtoSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals SpeedmapProtoSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := SpeedmapProtos.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o SpeedmapProtoSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := SpeedmapProtos.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o SpeedmapProtoSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := SpeedmapProtos.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// RSInfo starts a query for related objects on rs_info
func (o *SpeedmapProto) RSInfo(mods ...bob.Mod[*dialect.SelectQuery]) RSInfosQuery {
	return RSInfos.Query(append(mods,
		sm.Where(RSInfos.Columns.ID.EQ(psql.Arg(o.RSInfoID))),
	)...)
}

func (os SpeedmapProtoSlice) RSInfo(mods ...bob.Mod[*dialect.SelectQuery]) RSInfosQuery {
	pkRSInfoID := make(pgtypes.Array[int32], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkRSInfoID = append(pkRSInfoID, o.RSInfoID)
	}

	PKArgExpr := psql.Any(psql.Cast(psql.Arg(pkRSInfoID), "integer[]"))

	return RSInfos.Query(append(mods,
		sm.Where(RSInfos.Columns.ID.EQ(PKArgExpr)),
	)...)
}

func attachSpeedmapProtoRSInfo0(ctx context.Context, exec bob.Executor, count int, speedmapProto0 *SpeedmapProto, rsInfo1 *RSInfo) (*SpeedmapProto, error) {
	setter := &SpeedmapProtoSetter{
		RSInfoID: omit.From(rsInfo1.ID),
	}

	err := speedmapProto0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachSpeedmapProtoRSInfo0: %w", err)
	}

	return speedmapProto0, nil
}

func (speedmapProto0 *SpeedmapProto) InsertRSInfo(ctx context.Context, exec bob.Executor, related *RSInfoSetter) error {
	var err error

	rsInfo1, err := RSInfos.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachSpeedmapProtoRSInfo0(ctx, exec, 1, speedmapProto0, rsInfo1)
	if err != nil {
		return err
	}

	speedmapProto0.R.RSInfo = rsInfo1
	speedmapProto0.R.Loaded.RSInfo = true

	rsInfo1.R.SpeedmapProtos = append(rsInfo1.R.SpeedmapProtos, speedmapProto0)

	return nil
}

func (speedmapProto0 *SpeedmapProto) AttachRSInfo(ctx context.Context, exec bob.Executor, rsInfo1 *RSInfo) error {
	var err error

	_, err = attachSpeedmapProtoRSInfo0(ctx, exec, 1, speedmapProto0, rsInfo1)
	if err != nil {
		return err
	}

	speedmapProto0.R.RSInfo = rsInfo1
	speedmapProto0.R.Loaded.RSInfo = true

	rsInfo1.R.SpeedmapProtos = append(rsInfo1.R.SpeedmapProtos, speedmapProto0)

	return nil
}

type speedmapProtoWhere[Q psql.Filterable] struct {
	ID        psql.WhereMod[Q, int32]
	RSInfoID  psql.WhereMod[Q, int32]
	Protodata psql.WhereMod[Q, []byte]
}

func (speedmapProtoWhere[Q]) AliasedAs(alias string) speedmapProtoWhere[Q] {
	return buildSpeedmapProtoWhere[Q](buildSpeedmapProtoColumns(alias))
}

func buildSpeedmapProtoWhere[Q psql.Filterable](cols speedmapProtoColumns) speedmapProtoWhere[Q] {
	return speedmapProtoWhere[Q]{
		ID:        psql.Where[Q, int32](cols.ID.Expression),
		RSInfoID:  psql.Where[Q, int32](cols.RSInfoID.Expression),
		Protodata: psql.Where[Q, []byte](cols.Protodata.Expression),
	}
}

func (o *SpeedmapProto) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "RSInfo":
		rel, ok := retrieved.(*RSInfo)
		if !ok {
			return fmt.Errorf("speedmapProto cannot load %T as %q", retrieved, name)
		}

		o.R.RSInfo = rel
		o.R.Loaded.RSInfo = true

		if rel != nil {
			rel.R.SpeedmapProtos = SpeedmapProtoSlice{o}
		}
		return nil
	default:
		return fmt.Errorf("speedmapProto has no relationship %q", name)
	}
}

type speedmapProtoPreloader struct {
	RSInfo func(...psql.PreloadOption) psql.Preloader
}

func buildSpeedmapProtoPreloader() speedmapProtoPreloader {
	return speedmapProtoPreloader{
		RSInfo: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*RSInfo, RSInfoSlice](psql.PreloadRel{
				Name: "RSInfo",
				Sides: []psql.PreloadSide{
					{
						From:        SpeedmapProtos,
						To:          RSInfos,
						FromColumns: []string{"rs_info_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, RSInfos.Columns.Names(), opts...)
		},
	}
}

type speedmapProtoThenLoader[Q orm.Loadable] struct {
	RSInfo func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildSpeedmapProtoThenLoader[Q orm.Loadable]() speedmapProtoThenLoader[Q] {
	type RSInfoLoadInterface interface {
		LoadRSInfo(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return speedmapProtoThenLoader[Q]{
		RSInfo: thenLoadBuilder[Q](
			"RSInfo",
			func(ctx context.Context, exec bob.Executor, retrieved RSInfoLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadRSInfo(ctx, exec, mods...)
			},
		),
	}
}

// LoadRSInfo loads the speedmapProto's RSInfo into the .R struct
func (o *SpeedmapProto) LoadRSInfo(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.RSInfo = nil
	o.R.Loaded.RSInfo = false

	related, err := o.RSInfo(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.SpeedmapProtos = SpeedmapProtoSlice{o}

	o.R.RSInfo = related
	o.R.Loaded.RSInfo = true
	return nil
}

// LoadRSInfo loads the speedmapProto's RSInfo into the .R struct
func (os SpeedmapProtoSlice) LoadRSInfo(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	rsInfos, err := os.RSInfo(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.RSInfo = nil
		o.R.Loaded.RSInfo = true
	}
	// O(N+M) stitch via a map keyed by the join column (key -> []parent; was O(N*M)).
	speedmapProtoByKey := make(map[int32][]*SpeedmapProto, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}

		speedmapProtoByKey[o.RSInfoID] = append(speedmapProtoByKey[o.RSInfoID], o)
	}

	for _, rel := range rsInfos {

		owners, ok := speedmapProtoByKey[rel.ID]
		if !ok {
			continue
		}

		for _, o := range owners {

			// to-one: keep only the first matching child (matches the previous break)
			if o.R.RSInfo != nil {
				continue
			}

			rel.R.SpeedmapProtos = append(rel.R.SpeedmapProtos, o)

			o.R.RSInfo = rel

		}
	}

	return nil
}

type speedmapProtoJoins[Q dialect.Joinable] struct {
	typ    string
	RSInfo modAs[Q, rsInfoColumns]
}

func (j speedmapProtoJoins[Q]) aliasedAs(alias string) speedmapProtoJoins[Q] {
	return buildSpeedmapProtoJoins[Q](buildSpeedmapProtoColumns(alias), j.typ)
}

func buildSpeedmapProtoJoins[Q dialect.Joinable](cols speedmapProtoColumns, typ string) speedmapProtoJoins[Q] {
	return speedmapProtoJoins[Q]{
		typ: typ,
		RSInfo: modAs[Q, rsInfoColumns]{
			c: RSInfos.Columns,
			f: func(to rsInfoColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, RSInfos.NameExpr().As(to.Alias())).On(
						to.ID.EQ(cols.RSInfoID),
					))
				}

				return mods
			},
		},
	}
}
