// Code generated by BobGen psql v0.46.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"

	"github.com/aarondl/opt/omit"
	"github.com/gofrs/uuid/v5"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
	"github.com/stephenafamo/scan"
)

// Tenant is an object representing the database table.
type Tenant struct {
	ID int32 `db:"id,pk" `
	// for external use
	ExternalID uuid.UUID `db:"external_id" `
	Name       string    `db:"name" `
	APIKey     string    `db:"api_key" `
	Active     bool      `db:"active" `

	R tenantR `db:"-" `

	C tenantC `db:"-" `
}

// TenantSlice is an alias for a slice of pointers to Tenant.
// This should almost always be used instead of []*Tenant.
type TenantSlice []*Tenant

// Tenants contains methods to work with the tenant table
var Tenants = psql.NewTablex[*Tenant, TenantSlice, *TenantSetter]("", "tenant", buildTenantColumns("tenant"))

// TenantsQuery is a query on the tenant table
type TenantsQuery = *psql.ViewQuery[*Tenant, TenantSlice]

// tenantR is where relationships are stored.
type tenantR struct {
	Events EventSlice // event.event_tenant_id_fk
	// Loaded reports whether each relationship has been loaded.
	// A relationship's bool is set by Load*, Preload, ThenLoad, factory builds,
	// and to-one Attach/Insert operations. To-many Attach/Insert operations leave it unchanged.
	Loaded tenantRLoaded `db:"-" `
}

// tenantRLoaded tracks which relationships on Tenant have been loaded.
type tenantRLoaded struct {
	Events bool // event.event_tenant_id_fk
}

func buildTenantColumns(tableName string) tenantColumns {
	columnsExpr := expr.NewColumnsExpr(
		"id", "external_id", "name", "api_key", "active",
	)

	if tableName != "" {
		columnsExpr = columnsExpr.WithParent(tableName)
	}

	return tenantColumns{
		ColumnsExpr: columnsExpr,
		tableAlias:  tableName,
		ID:          buildTenantColumn(tableName, "id"),
		ExternalID:  buildTenantColumn(tableName, "external_id"),
		Name:        buildTenantColumn(tableName, "name"),
		APIKey:      buildTenantColumn(tableName, "api_key"),
		Active:      buildTenantColumn(tableName, "active"),
	}
}

type tenantColumns struct {
	expr.ColumnsExpr
	tableAlias string
	ID         tenantColumn
	ExternalID tenantColumn
	Name       tenantColumn
	APIKey     tenantColumn
	Active     tenantColumn
}

// Alias returns the current table alias for the columns set.
func (c tenantColumns) Alias() string {
	return c.tableAlias
}

// AliasedAs returns a copy of the columns set qualified by tableName.
func (tenantColumns) AliasedAs(tableName string) tenantColumns {
	return buildTenantColumns(tableName)
}

// Unqualified returns a copy of the columns set without table qualification.
func (c tenantColumns) Unqualified() tenantColumns {
	return buildTenantColumns("")
}

func buildTenantColumn(alias, name string) tenantColumn {
	return tenantColumn{
		Expression: psql.Quote(alias, name),
		alias:      alias,
		name:       name,
	}
}

type tenantColumn struct {
	psql.Expression
	alias string
	name  string
}

// Name returns the unqualified column name.
func (c tenantColumn) Name() string {
	return c.name
}

// ShouldOmitParens prevents automatic parenthesis wrapping in expression builders.
func (c tenantColumn) ShouldOmitParens() bool {
	return true
}

// TenantSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type TenantSetter struct {
	ID         omit.Val[int32]     `db:"id,pk" `
	ExternalID omit.Val[uuid.UUID] `db:"external_id" `
	Name       omit.Val[string]    `db:"name" `
	APIKey     omit.Val[string]    `db:"api_key" `
	Active     omit.Val[bool]      `db:"active" `
}

func (s TenantSetter) SetColumns() []string {
	vals := make([]string, 0, 5)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.ExternalID.IsValue() {
		vals = append(vals, "external_id")
	}
	if s.Name.IsValue() {
		vals = append(vals, "name")
	}
	if s.APIKey.IsValue() {
		vals = append(vals, "api_key")
	}
	if s.Active.IsValue() {
		vals = append(vals, "active")
	}
	return vals
}

func (s TenantSetter) Overwrite(t *Tenant) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.ExternalID.IsValue() {
		t.ExternalID = s.ExternalID.MustGet()
	}
	if s.Name.IsValue() {
		t.Name = s.Name.MustGet()
	}
	if s.APIKey.IsValue() {
		t.APIKey = s.APIKey.MustGet()
	}
	if s.Active.IsValue() {
		t.Active = s.Active.MustGet()
	}
}

func (s *TenantSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Tenants.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(
		bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.ID.IsUnset() {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(s.ID.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.ExternalID.IsUnset() {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(s.ExternalID.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.Name.IsUnset() {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(s.Name.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.APIKey.IsUnset() {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(s.APIKey.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.Active.IsUnset() {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(s.Active.MustGet()).WriteSQL(ctx, w, d, start)
		}))
}

func (s TenantSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s TenantSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 5)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.ExternalID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "external_id")...),
			psql.Arg(s.ExternalID),
		}})
	}

	if s.Name.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "name")...),
			psql.Arg(s.Name),
		}})
	}

	if s.APIKey.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "api_key")...),
			psql.Arg(s.APIKey),
		}})
	}

	if s.Active.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "active")...),
			psql.Arg(s.Active),
		}})
	}

	return exprs
}

// FindTenant retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindTenant(ctx context.Context, exec bob.Executor, IDPK int32, cols ...string) (*Tenant, error) {
	if len(cols) == 0 {
		return Tenants.Query(
			sm.Where(Tenants.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Tenants.Query(
		sm.Where(Tenants.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(Tenants.Columns.Only(cols...)),
	).One(ctx, exec)
}

// TenantExists checks the presence of a single record by primary key
func TenantExists(ctx context.Context, exec bob.Executor, IDPK int32) (bool, error) {
	return Tenants.Query(
		sm.Where(Tenants.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Tenant is retrieved from the database
func (o *Tenant) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Tenants.AfterSelectHooks.RunHooks(ctx, exec, TenantSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Tenants.AfterInsertHooks.RunHooks(ctx, exec, TenantSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Tenants.AfterUpdateHooks.RunHooks(ctx, exec, TenantSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Tenants.AfterDeleteHooks.RunHooks(ctx, exec, TenantSlice{o})
	case bob.QueryTypeMerge:
		ctx, err = Tenants.AfterMergeHooks.RunHooks(ctx, exec, TenantSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the Tenant
func (o *Tenant) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *Tenant) pkEQ() dialect.Expression {
	return psql.Quote("tenant", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Tenant
func (o *Tenant) Update(ctx context.Context, exec bob.Executor, s *TenantSetter) error {
	v, err := Tenants.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single Tenant record with an executor
func (o *Tenant) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Tenants.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Tenant using the executor
func (o *Tenant) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Tenants.Query(
		sm.Where(Tenants.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after TenantSlice is retrieved from the database
func (o TenantSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Tenants.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Tenants.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Tenants.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Tenants.AfterDeleteHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeMerge:
		ctx, err = Tenants.AfterMergeHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o TenantSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("tenant", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o TenantSlice) copyMatchingRows(from ...*Tenant) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o TenantSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Tenants.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Tenant:
				o.copyMatchingRows(retrieved)
			case []*Tenant:
				o.copyMatchingRows(retrieved...)
			case TenantSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Tenant or a slice of Tenant
				// then run the AfterUpdateHooks on the slice
				_, err = Tenants.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o TenantSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Tenants.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Tenant:
				o.copyMatchingRows(retrieved)
			case []*Tenant:
				o.copyMatchingRows(retrieved...)
			case TenantSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Tenant or a slice of Tenant
				// then run the AfterDeleteHooks on the slice
				_, err = Tenants.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// MergeMod modifies a merge query to run BeforeMergeHooks and AfterMergeHooks
// and updates the slice with the returned rows.
func (o TenantSlice) MergeMod() bob.Mod[*dialect.MergeQuery] {
	return bob.ModFunc[*dialect.MergeQuery](func(q *dialect.MergeQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Tenants.BeforeMergeHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Tenant:
				o.copyMatchingRows(retrieved)
			case []*Tenant:
				o.copyMatchingRows(retrieved...)
			case TenantSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Tenant or a slice of Tenant
				// then run the AfterMergeHooks on the slice
				_, err = Tenants.AfterMergeHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))
	})
}

func (o TenantSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals TenantSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Tenants.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o TenantSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Tenants.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o TenantSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Tenants.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// Events starts a query for related objects on event
func (o *Tenant) Events(mods ...bob.Mod[*dialect.SelectQuery]) EventsQuery {
	return Events.Query(append(mods,
		sm.Where(Events.Columns.TenantID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os TenantSlice) Events(mods ...bob.Mod[*dialect.SelectQuery]) EventsQuery {
	pkID := make(pgtypes.Array[int32], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "integer[]")),
	))

	return Events.Query(append(mods,
		sm.Where(psql.Group(Events.Columns.TenantID).OP("IN", PKArgExpr)),
	)...)
}

func insertTenantEvents0(ctx context.Context, exec bob.Executor, events1 []*EventSetter, tenant0 *Tenant) (EventSlice, error) {
	for i := range events1 {
		events1[i].TenantID = omit.From(tenant0.ID)
	}

	ret, err := Events.Insert(bob.ToMods(events1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertTenantEvents0: %w", err)
	}

	return ret, nil
}

func attachTenantEvents0(ctx context.Context, exec bob.Executor, count int, events1 EventSlice, tenant0 *Tenant) (EventSlice, error) {
	setter := &EventSetter{
		TenantID: omit.From(tenant0.ID),
	}

	err := events1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachTenantEvents0: %w", err)
	}

	return events1, nil
}

func (tenant0 *Tenant) InsertEvents(ctx context.Context, exec bob.Executor, related ...*EventSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	events1, err := insertTenantEvents0(ctx, exec, related, tenant0)
	if err != nil {
		return err
	}

	tenant0.R.Events = append(tenant0.R.Events, events1...)

	for _, rel := range events1 {
		rel.R.Tenant = tenant0
		rel.R.Loaded.Tenant = true
	}
	return nil
}

func (tenant0 *Tenant) AttachEvents(ctx context.Context, exec bob.Executor, related ...*Event) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	events1 := EventSlice(related)

	_, err = attachTenantEvents0(ctx, exec, len(related), events1, tenant0)
	if err != nil {
		return err
	}

	tenant0.R.Events = append(tenant0.R.Events, events1...)

	for _, rel := range related {
		rel.R.Tenant = tenant0
		rel.R.Loaded.Tenant = true
	}

	return nil
}

type tenantWhere[Q psql.Filterable] struct {
	ID         psql.WhereMod[Q, int32]
	ExternalID psql.WhereMod[Q, uuid.UUID]
	Name       psql.WhereMod[Q, string]
	APIKey     psql.WhereMod[Q, string]
	Active     psql.WhereMod[Q, bool]
}

func (tenantWhere[Q]) AliasedAs(alias string) tenantWhere[Q] {
	return buildTenantWhere[Q](buildTenantColumns(alias))
}

func buildTenantWhere[Q psql.Filterable](cols tenantColumns) tenantWhere[Q] {
	return tenantWhere[Q]{
		ID:         psql.Where[Q, int32](cols.ID.Expression),
		ExternalID: psql.Where[Q, uuid.UUID](cols.ExternalID.Expression),
		Name:       psql.Where[Q, string](cols.Name.Expression),
		APIKey:     psql.Where[Q, string](cols.APIKey.Expression),
		Active:     psql.Where[Q, bool](cols.Active.Expression),
	}
}

func (o *Tenant) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "Events":
		rels, ok := retrieved.(EventSlice)
		if !ok {
			return fmt.Errorf("tenant cannot load %T as %q", retrieved, name)
		}

		o.R.Events = rels
		o.R.Loaded.Events = true

		for _, rel := range rels {
			if rel != nil {
				rel.R.Tenant = o
				rel.R.Loaded.Tenant = true
			}
		}
		return nil
	default:
		return fmt.Errorf("tenant has no relationship %q", name)
	}
}

type tenantPreloader struct{}

func buildTenantPreloader() tenantPreloader {
	return tenantPreloader{}
}

type tenantThenLoader[Q orm.Loadable] struct {
	Events func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildTenantThenLoader[Q orm.Loadable]() tenantThenLoader[Q] {
	type EventsLoadInterface interface {
		LoadEvents(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return tenantThenLoader[Q]{
		Events: thenLoadBuilder[Q](
			"Events",
			func(ctx context.Context, exec bob.Executor, retrieved EventsLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadEvents(ctx, exec, mods...)
			},
		),
	}
}

// LoadEvents loads the tenant's Events into the .R struct
func (o *Tenant) LoadEvents(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Events = nil
	o.R.Loaded.Events = false

	related, err := o.Events(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.Tenant = o
		rel.R.Loaded.Tenant = true
	}

	o.R.Events = related
	o.R.Loaded.Events = true
	return nil
}

// LoadEvents loads the tenant's Events into the .R struct
func (os TenantSlice) LoadEvents(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	events, err := os.Events(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.Events = nil
		o.R.Loaded.Events = true
	}
	// O(N+M) stitch via a map keyed by the join column (key -> []parent; was O(N*M)).
	tenantByKey := make(map[int32][]*Tenant, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}

		tenantByKey[o.ID] = append(tenantByKey[o.ID], o)
	}

	for _, rel := range events {

		owners, ok := tenantByKey[rel.TenantID]
		if !ok {
			continue
		}

		for _, o := range owners {

			rel.R.Tenant = o
			rel.R.Loaded.Tenant = true

			o.R.Events = append(o.R.Events, rel)

		}
	}

	return nil
}

// tenantC is where relationship counts are stored.
type tenantC struct {
	Events *int64
}

// PreloadCount sets a count in the C struct by name
func (o *Tenant) PreloadCount(name string, count int64) error {
	if o == nil {
		return nil
	}

	switch name {
	case "Events":
		o.C.Events = &count
	}
	return nil
}

type tenantCountPreloader struct {
	Events func(...bob.Mod[*dialect.SelectQuery]) psql.Preloader
}

func buildTenantCountPreloader() tenantCountPreloader {
	return tenantCountPreloader{
		Events: func(mods ...bob.Mod[*dialect.SelectQuery]) psql.Preloader {
			return countPreloader[*Tenant]("Events", func(parent string) bob.Expression {
				// Build a correlated subquery: (SELECT COUNT(*) FROM related WHERE fk = parent.pk)
				if parent == "" {
					parent = Tenants.Alias()
				}

				subqueryMods := []bob.Mod[*dialect.SelectQuery]{
					sm.Columns(psql.Raw("count(*)")),

					sm.From(Events.NameAsExpr()),
					sm.Where(psql.Quote(Events.Alias(), "tenant_id").EQ(psql.Quote(parent, "id"))),
				}
				subqueryMods = append(subqueryMods, mods...)
				return psql.Group(psql.Select(subqueryMods...).Expression)
			})
		},
	}
}

type tenantCountThenLoader[Q orm.Loadable] struct {
	Events func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildTenantCountThenLoader[Q orm.Loadable]() tenantCountThenLoader[Q] {
	type EventsCountInterface interface {
		LoadCountEvents(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return tenantCountThenLoader[Q]{
		Events: countThenLoadBuilder[Q](
			"Events",
			func(ctx context.Context, exec bob.Executor, retrieved EventsCountInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCountEvents(ctx, exec, mods...)
			},
		),
	}
}

// LoadCountEvents loads the count of Events into the C struct
func (o *Tenant) LoadCountEvents(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	count, err := o.Events(mods...).Count(ctx, exec)
	if err != nil {
		return err
	}

	o.C.Events = &count
	return nil
}

// LoadCountEvents loads the count of Events for a slice in a single batch query
func (os TenantSlice) LoadCountEvents(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	// Build the IN arg expression from parent PKs

	pkID := make(pgtypes.Array[int32], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "integer[]")),
	))

	// countResult holds one scanned row from the batch count query.
	// FK columns are aliased to the parent PK column names for direct map lookup.
	type countResult struct {
		ID    int32
		Count int64
	}

	batchMods := []bob.Mod[*dialect.SelectQuery]{
		// SELECT fk AS parent_pk, count(*)
		sm.Columns(
			Events.Columns.TenantID.As("id"),
			psql.Raw("count(*) as count"),
		),
		// Single-hop: FROM related table directly
		sm.From(Events.NameAsExpr()),

		// WHERE fk IN (parent PKs)
		sm.Where(Events.Columns.TenantID.OP("IN", PKArgExpr)),
		// GROUP BY fk columns
		sm.GroupBy(Events.Columns.TenantID),
	}
	batchMods = append(batchMods, mods...)

	results, err := bob.All(ctx, exec,
		psql.Select(batchMods...),
		scan.StructMapper[countResult](),
	)
	if err != nil {
		return err
	}

	// Single-column FK: direct map lookup
	countMap := make(map[int32]int64, len(results))
	for _, r := range results {
		countMap[r.ID] = r.Count
	}
	for _, o := range os {
		if o == nil {
			continue
		}
		count := countMap[o.ID]
		o.C.Events = &count
	}

	return nil
}

type tenantJoins[Q dialect.Joinable] struct {
	typ    string
	Events modAs[Q, eventColumns]
}

func (j tenantJoins[Q]) aliasedAs(alias string) tenantJoins[Q] {
	return buildTenantJoins[Q](buildTenantColumns(alias), j.typ)
}

func buildTenantJoins[Q dialect.Joinable](cols tenantColumns, typ string) tenantJoins[Q] {
	return tenantJoins[Q]{
		typ: typ,
		Events: modAs[Q, eventColumns]{
			c: Events.Columns,
			f: func(to eventColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Events.NameExpr().As(to.Alias())).On(
						to.TenantID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
	}
}
