services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.4.0
    container_name: keycloak
    ports:
      - "9080:8080"
    environment:
      # Keycloak Database Configuration
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      # Keycloak Admin User
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      # Start Keycloak on server startup
      KC_HEALTH_ENABLED: "true"
      KC_PROXY: edge
      KC_HOSTNAME_STRICT_HTTPS: "false"
      # Additional options
      KC_HTTP_ENABLED: "true"
      KC_FEATURES: "token-exchange,client-secret-rotation"
    command:
      - start-dev
    # volumes:
    #   - ./keycloak-data:/opt/keycloak/data
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    # volumes:
    #   - ./postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
