// Code generated by BobGen psql v0.40.2. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var CarStateProtos = Table[
	carStateProtoColumns,
	carStateProtoIndexes,
	carStateProtoForeignKeys,
	carStateProtoUniques,
	carStateProtoChecks,
]{
	Schema: "",
	Name:   "car_state_proto",
	Columns: carStateProtoColumns{
		ID: column{
			Name:      "id",
			DBType:    "integer",
			Default:   "nextval('car_state_proto_id_seq'::regclass)",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		RSInfoID: column{
			Name:      "rs_info_id",
			DBType:    "integer",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Protodata: column{
			Name:      "protodata",
			DBType:    "bytea",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: carStateProtoIndexes{
		CarStateProtoPkey: index{
			Type: "btree",
			Name: "car_state_proto_pkey",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		CarProtoRSInfoIdx: index{
			Type: "btree",
			Name: "car_proto_rs_info_idx",
			Columns: []indexColumn{
				{
					Name:         "rs_info_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        false,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "car_state_proto_pkey",
		Columns: []string{"id"},
		Comment: "",
	},
	ForeignKeys: carStateProtoForeignKeys{
		CarStateProtoCarStateProtoRSInfoIDFkey: foreignKey{
			constraint: constraint{
				Name:    "car_state_proto.car_state_proto_rs_info_id_fkey",
				Columns: []string{"rs_info_id"},
				Comment: "",
			},
			ForeignTable:   "rs_info",
			ForeignColumns: []string{"id"},
		},
	},

	Comment: "",
}

type carStateProtoColumns struct {
	ID        column
	RSInfoID  column
	Protodata column
}

func (c carStateProtoColumns) AsSlice() []column {
	return []column{
		c.ID, c.RSInfoID, c.Protodata,
	}
}

type carStateProtoIndexes struct {
	CarStateProtoPkey index
	CarProtoRSInfoIdx index
}

func (i carStateProtoIndexes) AsSlice() []index {
	return []index{
		i.CarStateProtoPkey, i.CarProtoRSInfoIdx,
	}
}

type carStateProtoForeignKeys struct {
	CarStateProtoCarStateProtoRSInfoIDFkey foreignKey
}

func (f carStateProtoForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.CarStateProtoCarStateProtoRSInfoIDFkey,
	}
}

type carStateProtoUniques struct{}

func (u carStateProtoUniques) AsSlice() []constraint {
	return []constraint{}
}

type carStateProtoChecks struct{}

func (c carStateProtoChecks) AsSlice() []check {
	return []check{}
}
