// Code generated by BobGen psql v0.40.2. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var EventExts = Table[
	eventExtColumns,
	eventExtIndexes,
	eventExtForeignKeys,
	eventExtUniques,
	eventExtChecks,
]{
	Schema: "",
	Name:   "event_ext",
	Columns: eventExtColumns{
		EventID: column{
			Name:      "event_id",
			DBType:    "integer",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		ExtraInfo: column{
			Name:      "extra_info",
			DBType:    "jsonb",
			Default:   "'{}'::jsonb",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: eventExtIndexes{
		EventExtPkey: index{
			Type: "btree",
			Name: "event_ext_pkey",
			Columns: []indexColumn{
				{
					Name:         "event_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "event_ext_pkey",
		Columns: []string{"event_id"},
		Comment: "",
	},
	ForeignKeys: eventExtForeignKeys{
		EventExtEventExtEventIDFkey: foreignKey{
			constraint: constraint{
				Name:    "event_ext.event_ext_event_id_fkey",
				Columns: []string{"event_id"},
				Comment: "",
			},
			ForeignTable:   "event",
			ForeignColumns: []string{"id"},
		},
	},

	Comment: "additional information about a recorded event",
}

type eventExtColumns struct {
	EventID   column
	ExtraInfo column
}

func (c eventExtColumns) AsSlice() []column {
	return []column{
		c.EventID, c.ExtraInfo,
	}
}

type eventExtIndexes struct {
	EventExtPkey index
}

func (i eventExtIndexes) AsSlice() []index {
	return []index{
		i.EventExtPkey,
	}
}

type eventExtForeignKeys struct {
	EventExtEventExtEventIDFkey foreignKey
}

func (f eventExtForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.EventExtEventExtEventIDFkey,
	}
}

type eventExtUniques struct{}

func (u eventExtUniques) AsSlice() []constraint {
	return []constraint{}
}

type eventExtChecks struct{}

func (c eventExtChecks) AsSlice() []check {
	return []check{}
}
