// Code generated by BobGen psql v0.40.2. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var MSGStateProtos = Table[
	msgStateProtoColumns,
	msgStateProtoIndexes,
	msgStateProtoForeignKeys,
	msgStateProtoUniques,
	msgStateProtoChecks,
]{
	Schema: "",
	Name:   "msg_state_proto",
	Columns: msgStateProtoColumns{
		ID: column{
			Name:      "id",
			DBType:    "integer",
			Default:   "nextval('msg_state_proto_id_seq'::regclass)",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		RSInfoID: column{
			Name:      "rs_info_id",
			DBType:    "integer",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Protodata: column{
			Name:      "protodata",
			DBType:    "bytea",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: msgStateProtoIndexes{
		MSGStateProtoPkey: index{
			Type: "btree",
			Name: "msg_state_proto_pkey",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		MSGProtoRSInfoIdx: index{
			Type: "btree",
			Name: "msg_proto_rs_info_idx",
			Columns: []indexColumn{
				{
					Name:         "rs_info_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        false,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "msg_state_proto_pkey",
		Columns: []string{"id"},
		Comment: "",
	},
	ForeignKeys: msgStateProtoForeignKeys{
		MSGStateProtoMSGStateProtoRSInfoIDFkey: foreignKey{
			constraint: constraint{
				Name:    "msg_state_proto.msg_state_proto_rs_info_id_fkey",
				Columns: []string{"rs_info_id"},
				Comment: "",
			},
			ForeignTable:   "rs_info",
			ForeignColumns: []string{"id"},
		},
	},

	Comment: "Messages extracted from race_state_proto",
}

type msgStateProtoColumns struct {
	ID        column
	RSInfoID  column
	Protodata column
}

func (c msgStateProtoColumns) AsSlice() []column {
	return []column{
		c.ID, c.RSInfoID, c.Protodata,
	}
}

type msgStateProtoIndexes struct {
	MSGStateProtoPkey index
	MSGProtoRSInfoIdx index
}

func (i msgStateProtoIndexes) AsSlice() []index {
	return []index{
		i.MSGStateProtoPkey, i.MSGProtoRSInfoIdx,
	}
}

type msgStateProtoForeignKeys struct {
	MSGStateProtoMSGStateProtoRSInfoIDFkey foreignKey
}

func (f msgStateProtoForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.MSGStateProtoMSGStateProtoRSInfoIDFkey,
	}
}

type msgStateProtoUniques struct{}

func (u msgStateProtoUniques) AsSlice() []constraint {
	return []constraint{}
}

type msgStateProtoChecks struct{}

func (c msgStateProtoChecks) AsSlice() []check {
	return []check{}
}
