name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
  pull_request:
    types: [opened, reopened]

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: "./go.mod"

      - name: Install Dependencies
        run: go mod download

      - name: Test
        run: go test `go list ./... | grep pkg/grpc` -p 1 -race -coverprofile=coverage.txt -covermode=atomic -gcflags=-l
